// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WordsCombiner.Server.Data;

#nullable disable

namespace WordsCombiner.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230409021552_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WordsCombiner.Shared.Model.JapaneseWord", b =>
                {
                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PartOfSpeech")
                        .HasColumnType("int");

                    b.HasKey("Value");

                    b.ToTable("JapaneseWords");
                });
#pragma warning restore 612, 618
        }
    }
}
